### PR TITLE
Adds login_url to login_protection to allow https redirection properly

### PR DESCRIPTION
**Pull request by jasonbuehler**
I was having a problem with my application being redirected to a path with http instead of https. This allows the full url to be passed along with the secure protocol on this redirection.

### CODE REVIEW

**Comment by kevinhughes27** [comment]
interesting - kind of makes sense. Do you think this is the cause of #193?

Code lgtm, @gmalette can you take a look as well

**Comment by jasonbuehler** [comment]
It sure looks like that could be the same issue. My problem was occurring on oauth redirection to the application, not during app authorization but when I hit actions directly that were wrapped in the shopify_session around filter. I hadn't actually tried authorizing my app from a shop for a while so it could have been there too. I think I had converted to https since the last time I authorized the app from a shop so the problem could have been present and I hadn't seen it yet.

**Comment by gmalette** [comment]
@kevinhughes27 I don't know enough in this part to properly review, you know anyone that would?

**Comment by kevinhughes27** [comment]
okay no big deal I am good with this change just thought you might want to take a look. I will :tophat: on monday and then merge

**Comment by kevinhughes27** [comment]
I :tophat:ed and this works fine. I did notice that both this branch and master don't load the ESDK properly after install but thats an unrelated thing to look into.

Thanks for the PR

**Pull request merged**
