### PR TITLE
Clarify how nested routes affect Rails routing

### PR DESCRIPTION
**Pull request by davetron5000**
# Problem

If you follow the instructions to set up your app, then decide to use nested routes, things don't work as advertised.  See #603.  You need to also know that the engine doesn't render the Shopify Admin UI so you have to route to that *and* you have to know that going to that url triggers the "add your app to shopify" UI.  When you are totally new to this + shopify, these things are not obvious.

# Solution

Document it.

### CODE REVIEW

**Comment by katiedavis** [comment]
Hi @davetron5000
Thanks for your contribution, we're looking into it. In the meantime, would you mind signing the CLA? https://cla.shopify.com/
Thanks!

**Comment by davetron5000** [comment]
done

**Comment by davetron5000** [comment]
Gonna bump this (promise this is the only time I will).  This is a simple enough doc change so maybe it can merged?  If not, feel free to close

**Comment by nwtn** [comment]
@davetron5000 thanks so much for this. I’ll sort out the rebase and merge this today.

**Pull request merged**
