### PR TITLE
Add App Proxy Controller Generator && Add Table of Contents to README

### PR DESCRIPTION
**Pull request by ashmaroli**
A Table of Contents to navigate through our README file

### CODE REVIEW

**Comment by ashmaroli** [comment]
Okay, I didnt expect all 12 commits to be on this branch. Must be coz I merged my fork's `master` branch with my `app_proxy` branch before those commits got merged to the upstream branch.

**Comment by kevinhughes27** [comment]
Up to you - we can split this out and merge now or wait until your other PR is merged

**Comment by ashmaroli** [comment]
Lets wait, coz the ToC contains links to changes made in the other PR.

**Comment by kevinhughes27** [comment]
Can we still keep these PRs separate. Thanks

**Comment by ashmaroli** [comment]
I dont mind, but wont they conflict each other? I thought this way was easier for you. All changes in one place.

**Comment by kevinhughes27** [comment]
I would rather merge incremental changes one at a time. Whichever you prefer to split out first. Looks like the table of contents would be easy and there is still some debate on the proxy generator.

**Comment by ashmaroli** [comment]
I understand that, but the ToC references sections added in #295.

**Comment by kevinhughes27** [comment]
True - we could remove that part of the TOC and then add it back in the next PR

**Comment by ashmaroli** [comment]
So should I
 1. Try resetting my master branch
 2. Create another branch and incorporate just the ToC
 3. Create another PR

or is there a better solution?

**Comment by kevinhughes27** [comment]
I recommend `#2`

**Pull request closed without merging**
