### PR TITLE
Test against Ruby 2.7

### PR DESCRIPTION
**Pull request by sergey-alekseev**
Ruby 2.7 [was released](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/) on 25 Dec 2019 and the latest version is 2.7.1

### CODE REVIEW

**Comment by sergey-alekseev** [comment]
I signed CLA.

**Comment by sergey-alekseev** [comment]
Can you please rerun the CLA check, so the PR's status is green? 🙏 🟢

**Comment by tanema** [comment]
It seems like you probably opened the second one to re-trigger the CLA so I will close this one. Thanks for your help!

**Comment by sergey-alekseev** [comment]
@tanema I suppose you mean https://github.com/Shopify/shopify_api/pull/720. It's in a different repo :wink:   

Thanks for merging my MRs 🙏

**Comment by tanema** [comment]
Ah! you're right! That will teach me to merge before finishing my coffee.

**Pull request merged**
