### PR TITLE
Require rails > 5.2.1

### PR DESCRIPTION
**Pull request by chrisbutcher**
Follow-up to https://github.com/Shopify/shopify_app/issues/600
Closes https://github.com/Shopify/shopify/issues/205174

See the CHANGELOG for details.

### CODE REVIEW

**Comment by nwtn** [comment]
We can’t bump to 9.1 because (I believe) there are breaking changes on master that haven’t been released. If this can wait, we can merge this to master without the version bump; if you need us to do a release right away we’ll have to go to 10.0

**Comment by chrisbutcher** [comment]
I can do the changelog / version.rb changes in a separate commit per https://github.com/Shopify/shopify_api/blob/master/RELEASING if you prefer.

**Comment by chrisbutcher** [comment]
> If this can wait

Thanks Dave! This needs to ship before the 2019-07 API version stabilizes on July 1st, so I think it depends on if we think those other changes will make it in sooner or later.

**Comment by nwtn** [comment]
@chrisbutcher ya, if you could do a separate PR for the 10.0 release, we can merge this now and make sure the release goes out this week.

**Comment by chrisbutcher** [comment]
Thanks @nwtn ! To be clear, I'll merge only the functional changes to `shopify_app.gemspec` here in this PR, and open 2nd PR to to bump to 10.0 in version.rb and start updating the Changelog.

If that sounds good, can I have a 👍 ?

**Pull request merged**
