### PR TITLE
Nicer installation page

### PR DESCRIPTION
**Pull request by christianblais**
This simply add a bit of CSS to the default installation page. I'm no designer, so feel free to question my CSS.

Before:

screen shot 2015-11-13 at 5 51 52 pm

After:

screen shot 2015-11-13 at 5 49 32 pm

@kevinhughes27

### CODE REVIEW

**Comment by kevinhughes27** [comment]
Yeah I'm all for this! (haven't looked at the code though and I'm on
vacation)

**Comment by christianblais** [comment]
@qq99 mind to give this a quick review?

**Comment by qq99** [comment]
Looks way nicer!

**Comment by ckhatton** [comment]
:+1: Noice!

**Comment by kevinhughes27** [comment]
:clap:

**Pull request merged**
