### PR TITLE
 remove “third-party” from ITP copy

### PR DESCRIPTION
**Pull request by nwtn**
This is an MVP fix, English-only, for the copy in the ITP flow.

~(the updated yarn lock is unrelated, but should be committed)~

### CODE REVIEW

**Comment by tiffanytse** [comment]
So the yarn updates are in another PR I assume? 

Otherwise LGTM. 👍

**Comment by nwtn** [comment]
> So the yarn updates are in another PR I assume?

Ya I’m not sure which PR this was from, but it looks like maybe `yarn install` wasn’t run on a previous commit/PR that changed the deps.

On second thought, though, I’m going to split that into a separate PR.

**Comment by gfscott** [comment]
Since the English copy change is approved I've sent it to translation. PR can merge once that check passes.

**Comment by nwtn** [comment]
i need to do a release, so i've made translations async

**Pull request merged**
