### PR TITLE
Adds trial days option to recurring subscriptions

### PR DESCRIPTION
**Pull request by ivorpad**
### What this PR does

Allows passing trial_days to the billings config

### Reviewer's guide to testing

Configure billing with a trial:

```ruby
config.billing = ShopifyApp::BillingConfiguration.new(
  charge_name: "My app billing charge",
  amount: 5,
  interval: ShopifyApp::BillingConfiguration::INTERVAL_EVERY_30_DAYS,
  currency_code: "USD", # Only supports USD for now
  trial_days: 7,
)
```

When passing `trial_days`, expected:

Screenshot 2022-07-06 at 16 55 40

When _not_ passing `trial_days`, expected:

Screenshot 2022-07-06 at 16 57 46

### Things to focus on

1. Tests are passing
2. Trial in billing

### Checklist

Before submitting the PR, please consider if any of the following are needed:

- ~[x] Update `CHANGELOG.md` if the changes would impact users~
- ~[x] Update `README.md`, if appropriate.~
- ~[x] Update any relevant pages in `/docs`, if necessary~
- ~[x] For security fixes, the [Disclosure Policy](https://github.com/Shopify/shopify_app/blob/master/SECURITY.md#disclosure-policy) must be followed.~

### CODE REVIEW

**Comment by ivorpad** [comment]
Is there anyone here who can review? 

cc @paulomarg

**Comment by Keemtaker** [comment]
Any updates on this @ivorpad

**Comment by Keemtaker** [comment]
> @Keemtaker I think this has been added in a recent update. I will close this PR.

I actually cant find it in the source code. Also this does not work as 'trial days' is an unknown keyword. I am using gem version  'shopify_app', '~> 21.1.1'

`config.billing = ShopifyApp::BillingConfiguration.new(
    charge_name: "My app",
    amount: 5,
    trial_days: 7,
    interval: ShopifyApp::BillingConfiguration::INTERVAL_EVERY_30_DAYS,
    currency_code: "USD", # Only supports USD for now
  )`

Any ideas on how to add trial days to my billing config  @ivorpad ?

**Comment by Keemtaker** [comment]
Hi @ivorpad , can you please reopen the pull request? It was not merged into this repository rather it was merged into a forked repo https://github.com/dormi/shopify_app . So it is not available in this repo

**Pull request closed without merging**
