### PR TITLE
Rails 6.1 not yet supported

### PR DESCRIPTION
**Pull request by andyw8**
Before submitting the PR, please consider if any of the following are needed:

- [x] Update `CHANGELOG.md` if the changes would impact users
- [x] Update `README.md`, if appropriate.
- [ ] Update any relevant pages in `docs/`, if necessary
- [ ] For security fixes, the [Disclosure Policy](https://github.com/Shopify/shopify_app/blob/master/SECURITY.md#disclosure-policy) must be followed.

### CODE REVIEW

**Review by mllemango — APPROVED** [review]

**Review by alexaitken — APPROVED** [review]

**Comment by axlekb** [comment]
Just to clarify, this would only be for an embedded app, right?

**Comment by andyw8** [comment]
@axlekb Correct. Using the [shopify_api](https://github.com/Shopify/shopify_api) gem directly is fine.

**Comment by axlekb** [comment]
Hi @andyw8, yes, I am aware that API would be unaffected as it doesn't require any cookies, however I was more wondering about cookies for oauth portion of this gem.  We have a non-embedded app, and we are running 6.1...  We haven't noticed any problems, but just want to make sure that I'm not missing anything.

**Comment by kirillplatonov** [comment]
Hey @andyw8 👋

Does it really mandatory to restrict the Rails version to be < 6.1?
I'm using shopify_app 16.1 with an embedded app with no issues. The only change that is needed is enabling old SameSite cookies protection in Rails config like this:
```ruby
# config/application.rb

config.load_defaults 6.1
config.action_dispatch.cookies_same_site_protection = nil
```

**Pull request merged**
