### PR TITLE
Packaging for release 7.2.7

### PR DESCRIPTION
**Pull request by Hammadk**
Closes https://github.com/Shopify/shopify_app/issues/407

### CODE REVIEW

**Comment by Hammadk** [comment]
Rails 5 builds are failing with the following errors:
* `Gem Load Error is: undefined method 'alias_method_chain' for ActiveResource::Connection:Class`
* `NoMethodError: undefined method 'raise_in_transactional_callbacks=' for ActiveRecord::Base:Class`

**Comment by kevinhughes27** [comment]
I think we can just remove the calls to `raise_in_transactional_callbacks` as its just in our example and test dummy. Not sure about the other issue - maybe bump the required version of the api gem?

**Comment by kevinhughes27** [comment]
we might need to update the tests to use the new rails controller testing style of `params: { #the params }` instead of just keyword args.

**Comment by Hammadk** [comment]
Yep, I'll think about how we can make those changes so they are backward compatible with Rails 4 tests

**Comment by kevinhughes27** [comment]
We could also drop support for rails 4

**Comment by SebastianSzturo** [comment]
@Hammadk Can I slip in #409 before we release 7.2.7? 😅

**Comment by Hammadk** [comment]
@SebastianSzturo Sure! Your tests in your PR are failing at the moment. Some of the commits in this PR are trying to fix those failures -- so you'll have to duplicate some of this work if you want the tests to pass.

I recommend that we get this PR out, and then we can release your's right after

**Comment by Hammadk** [comment]
@kevinhughes27 @SebastianSzturo: We had to choose between dropping support for Rails 4, or coming up with an alternate solution. I decided against dropping support for Rails 4 because that would require us to add a runtime dependency for `gem 'activeresource', github: 'rails/activeresource'`. That points to the master branch of `activeresource` on github and I feel that's a little heavy-handed.

Instead I made the following changes:
* Update our Rails 5 tests to work with Rails `5.0.2`. This version of Rails 5 still supports Rails 4 test syntax
* Change the `'shopify_api` version to `'>= 4.3.2'`. This [version relaxes the ruby requirement](https://github.com/Shopify/shopify_api/blob/master/CHANGELOG#L51-L53) to ruby `> 2.0`. That means we don't need extra tests for ruby `2.2.2` so I have removed those.

What do you think about this approach? When a new version of active resource is released, we should drop support for Rails 4.

**Comment by kevinhughes27** [comment]
Sounds good to me! Thanks @Hammadk

**Comment by kevinhughes27** [comment]
@rafaelfranca is there a reason the newer version of active resource hasn't shipped yet that you are aware of?

**Comment by rafaelfranca** [comment]
Mostly because I was trying to come up with a version of Active Resource that supports both Rails 4 and Rails 5. It is ready since a few months ago but now it requires more work. I can work on it in the next days.

**Comment by kevinhughes27** [comment]
Sweet! We get a fair number of people posting issues here who miss the detail in the readme about using the master branch of active resource for rails 5 so it would definitely help to get a release!

**Comment by rafaelfranca** [comment]
Can you test the master branch? It is ready for release, I just need to test Shopify on it.

**Comment by kevinhughes27** [comment]
In Shopify or here? I think our rails 5 gemfile already uses it https://github.com/Shopify/shopify_app/blob/master/Gemfile.rails50#L5

**Comment by rafaelfranca** [comment]
Cool, so we just need to trigger a new build. Let me do that

**Comment by rafaelfranca** [comment]
5.0.0 released

**Comment by Hammadk** [comment]
Thanks, Rafael! I spoke with Kevin and we are going to:
* Release this PR as `v7.2.7`
* Add Sebastian's PR and release that as `v7.2.8`

After that, we'll create another PR
* Drop support for Rails 4
* Require ActiveResource 5.0
* Update the test syntax 
* Release as `v7.3.0`

**Pull request merged**
