### PR TITLE
[2/2] Documentation - Create contributing guide and default issue templates

### PR DESCRIPTION
**Pull request by NabeelAhsen**
## What this PR does

> This is part 2 of 2. Depends on part 1 to ship.
> Part 1: https://github.com/Shopify/shopify_app/pull/1195

* Introduces a `CONTRIBUTING.md` file
* Restructures of the ISSUE_TEMPLATE to use the new way of doing it: https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
  * Introduces a `bug-report.md` template for issues
  * Introduces a `feature-request.md` template for issues
* Updates the existing PULL_REQUEST_TEMPLATE.md

## Reviewer's guide to testing

This change is most easily tested by reading the CONTRIBUTING.md doc found on this branch: 

https://github.com/Shopify/shopify_app/tree/documentation/add-contributing-guide

## Things to focus on

1. Is the CONTRIBUTING.md too opinionated?
2. Do the templates make sense?
3. Do the links all work?

## Checklist

Before submitting the PR, please consider if any of the following are needed:

- [x] Update `CHANGELOG.md` if the changes would impact users
- [x] Update `README.md`, if appropriate.
- [x] Update any relevant pages in `/docs`, if necessary
- [x] For security fixes, the [Disclosure Policy](https://github.com/Shopify/shopify_app/blob/master/SECURITY.md#disclosure-policy) must be followed.

### CODE REVIEW

**Comment by paulomarg** [comment]
Ccing @gfscott here as well, if you have time to check this out!

**Review by nicolemackin — APPROVED** [review]
This is looking really good! I've left a few notes, but overall the content is clear and easy to follow. You may be able to simplify some of the content as you explain a lot of the sections in the issue templates themselves.

**Review by paulomarg — APPROVED** [review]
LGTM!

**Review by rezaansyed — APPROVED** [review]
LGTM!

**Pull request merged**
