### PR TITLE
Allow override myshopify_domain from shopify_app.yml

### PR DESCRIPTION
**Pull request by kmcphillips**
@jamesmacaulay @awd @ilikeorangutans 

Allow us to override the `myshopify_domain` from inside the `shopify_app.yml`. For internal use.

Bumps gem version to `5.0.2`.

### CODE REVIEW

**Comment by awd** [comment]
Noticed there was some coverage here for the existing keys:
https://github.com/Shopify/shopify_app/blob/af4265a30893444f0eecee6ff22196df5c04725c/test/lib/shopify_app/configuration_test.rb#L13-L17

Want me to add `myshopify_domain` to this (and any others) test?

**Comment by kmcphillips** [comment]
Sure!

**Comment by awd** [comment]
Alright, coverage has been added.

This LGTM :wink:

**Comment by ilikeorangutans** [comment]
:+1:

**Pull request merged**
