### PR TITLE
Add QUICKSTART to gh-pages

### PR DESCRIPTION
**Pull request by ashmaroli**
Currently, the link to Quickstart follows the page on the master branch instead of gh-pages.
This PR changes that and additionally syncs the index page to README on master

- [x] Add Quickstart page
- [x] Update link href in index.md
- [x] Sync Index to README on master

### CODE REVIEW

**Comment by kevinhughes27** [comment]
I am happy to merge this but just a heads up that I think we're removing the gh-pages branch and just linking to the repo itself everywhere

**Comment by ashmaroli** [comment]
oh..kay.. that move would eliminate the need to have the two documents synced and up-to-date.

**Comment by kevinhughes27** [comment]
Yup thats why I want to go that route

**Comment by ashmaroli** [comment]
can this be unmerged?
The link to quickstart is throwing a 404..

**Comment by kevinhughes27** [comment]
I wondered if it would. Its also impossible to test. You can click revert and open a PR

**Comment by ashmaroli** [comment]
do you think a quickstart.html would fix the 404? Hope thats what jekyll expects..

**Comment by kevinhughes27** [comment]
not sure but I am happy to try it out and see

**Pull request merged**
