### PR TITLE
Bypass application layout rendering for SessionsController

### PR DESCRIPTION
**Pull request by mariusbutuc**
The SessionsController inherits rendering using the application layout.

By default, render with no layout at all.

/review @kevinhughes27 @alexcoco @swalkinshaw
/cc @nickhoffman

### CODE REVIEW

**Comment by alexcoco** [comment]
The new action should be rendered without a layout, why not update the session concern and set layout false for that action

**Comment by nickhoffman** [comment]
@alexcoco, what's the benefit of specifying no layout for the `new` action only?

**Comment by alexcoco** [comment]
The difference is that if someone inherits this controller then you're disabling it for all the actions even the ones that they add. I rather it be more explicit.

**Comment by nickhoffman** [comment]
I usually err on the side of explicitness too. However, I figured that inheriting from this controller and adding actions is uncommon, and when it does occur, the application's default layout wouldn't be wanted. But if your experience says otherwise, :+1:

**Comment by kevinhughes27** [comment]
I would prefer the explicitness as well

**Comment by mariusbutuc** [comment]
Disabling the layout rendering moved into the concern, and it is now scoped to the `#new` action only, as of https://github.com/Shopify/shopify_app/commit/069d708e9f6e204d12b449d558cd4f6aef4d3434.

@kevinhughes27 @alexcoco @nickhoffman please have another look.

**Comment by nickhoffman** [comment]
Code LGTM. :ship: once you bump the version and CI is green.

**Comment by kevinhughes27** [comment]
👍

**Comment by alexcoco** [comment]
👍

**Pull request merged**
