### PR TITLE
Change class monkeypatch to module monkeypatch

### PR DESCRIPTION
**Pull request by gmalette**
@kevinhughes27 @nwtn 

This will help me test generators in another gem

### CODE REVIEW

**Comment by kevinhughes27** [comment]
:+1:

Those helpers pretty much come directly from thoughbot/clearance, I may have had to change them a bit. I feel like they should just be party of rails

**Comment by gmalette** [comment]
I totally agree, but the gem I'm working on depends on how `ShopifyApp` does things, so I can't go half-measures. If the generators change, the gem's tests should break.

**Comment by kevinhughes27** [comment]
:+1:

**Comment by nwtn** [comment]
lgtm

**Pull request merged**
