### PR TITLE
when app proxy verification fails, send 403 instead of 401

### PR DESCRIPTION
**Pull request by mikeyhew**
Fix for #318

### CODE REVIEW

**Comment by kevinhughes27** [comment]
Can you add to the CHANGELOG please

**Comment by mikeyhew** [comment]
@kevinhughes27 sure. To 7.1.0 or 7.1.1?

**Comment by mikeyhew** [comment]
I added it to 7.1.0, let me know if that's wrong

**Comment by ashmaroli** [comment]
@mikeyhew, The changelog is now a Markdown document. Please rebase and add to `CHANGELOG.md` instead.

**Comment by mikeyhew** [comment]
Thanks @ashmaroli - I forgot to pull from upstream before I started :sweat_smile:

**Comment by ashmaroli** [comment]
v7.1.1 got released before this got merged. You'll hv to update changelog again..

**Comment by kevinhughes27** [comment]
Can you rebase this so we can get it in version 8?

**Comment by mikeyhew** [comment]
@kevinhughes27 sorry I didn't get to this earlier. I don't think it's much of a breaking change, do you think it can make it into the next minor or patch release?

**Comment by kevinhughes27** [comment]
of course!

**Pull request merged**
