### PR TITLE
Enforce presence of application key and secret during initialization

### PR DESCRIPTION
**Pull request by tjoyal**
Thoughts on making it explicit when the key is not set when it is expected for it to be present so it fail fast?

### CODE REVIEW

**Comment by andyw8** [comment]
I support this.

**Comment by tjoyal** [comment]
I ended up with this in my app, not sure if we prefer that:
```rb
  config.api_key = ENV.fetch('SHOPIFY_API_KEY', '').presence || raise("Missing SHOPIFY_API_KEY")
  config.secret = ENV.fetch('SHOPIFY_API_SECRET', '').presence || raise("Missing SHOPIFY_API_SECRET")
```

I use `presence` as I use dotenv and have this so the keys are git versioned but not the secrets:
```
# .env
SHOPIFY_API_KEY=
SHOPIFY_API_SECRET=

# .env.local
SHOPIFY_API_KEY=the-actual-key
SHOPIFY_API_SECRET=the-actual-key

# .gitignore
.env.local
```

**Comment by paulomarg** [comment]
I actually like throwing a more specific error if one of the keys isn't present, it can be a bit of a pain point when apps start up without the necessary envs and fail later on for seemingly random reasons.

**Review by tanema — APPROVED** [review]

**Comment by andyw8** [comment]
@tjoyal I think this may be causing some problems: https://github.com/Shopify/shopify-app-cli/issues/1006

**Comment by tjoyal** [comment]
@andyw8 To make sure we are on the same page, I do not think we are challenging here the fact that is raises but rather the low quality error message? Seems like a fair ask.

**Comment by andyw8** [comment]
@tjoyal The error message is a secondary concern. But I think enforcing that the env vars are always present might have impacted how the generator runs. We're still investigating, no need to take action yet.

**Comment by andyw8** [comment]
https://github.com/Shopify/shopify-app-cli/pull/1026

**Comment by andyw8** [comment]
https://github.com/Shopify/shopify_app/pull/1144

**Pull request merged**
