### PR TITLE
chore: remove unsupported legacy EASDK examples

### PR DESCRIPTION
**Pull request by gf3**
Do not include examples of unsupported features

### CODE REVIEW

**Comment by nwtn** [comment]
@gf3 can you also remove the calls to the unsupported methods from the views?

**Comment by gf3** [comment]
i thought i did, but i’ll have another look

**Comment by nwtn** [comment]
my bad, i was looking on master. 🤦‍♂️ sorry about that

**Comment by NatMorcos** [comment]
removing the `inputModal` function and the associated call from the view make sense. how does the icon relate to it?

**Comment by nwtn** [comment]
icon is now set in partner dashboard, the easdk bit does nothing anymore

**Comment by gf3** [comment]
@NatMorcos the `icon` for embedded apps is now set through the partners dashboard

here's a list of unsupported features and quirks if you're interested: 
https://github.com/Shopify/app-bridge/issues/456

**Pull request merged**
