### PR TITLE
Extract HomeController generator

### PR DESCRIPTION
**Pull request by gmalette**
I don't know why someone would want `ShopifyApp` to create `HomeController` for them, but I didn't want to take product decisions. I just extracted it from `InstallGenerator`, so now it only runs when you do `rails g shopify_app` and not `rails g shopify_app:install`.

The reason behind this PR is that the generator breaks any existing app that have a `root` route, so basically every app.

@Krystosterone @kevinhughes27

### CODE REVIEW

**Comment by Krystosterone** [comment]
This makes sense and will really help us for `shopify_app_platform` :+1:

**Comment by gmalette** [comment]
@nwtn

**Comment by kevinhughes27** [comment]
Yup this makes sense. The non-full generator isn't as commonly used so I'm not surprised to find usage issues with it (most people just run the full generator). This solution makes sense.

The main reason for the home_controller was to showcase how to setup the basic ESDK views and also to show the AuthenticatedController which should be inherited from.

**Comment by nwtn** [comment]
lgtm

**Comment by gmalette** [comment]
I'll bump the version

**Comment by gmalette** [comment]
> The main reason for the home_controller was to showcase how to setup the basic ESDK

That makes sense

**Comment by Krystosterone** [comment]
:tada:

**Pull request merged**
