### PR TITLE
Bumping version

### PR DESCRIPTION
**Pull request by batasrki**
@kevinhughes27 @nwtn @Hammadk I'm bumping the version here. Are there any other places I need to consider?

### CODE REVIEW

**Comment by kevinhughes27** [comment]
👍

**Comment by Hammadk** [comment]
LGTM. Can you please create a 7.0.9 tag as well?

**Comment by batasrki** [comment]
@Hammadk I should be tagging off the merged master, right?

**Comment by Hammadk** [comment]
@batasrki Yeah, we can create a tag once this is merged.

**Pull request merged**
