### PR TITLE
Revert "Revert "Fix return_to address in Safari after enable_cookies and grated_storage_access""

### PR DESCRIPTION
**Pull request by hurracrane**
Reverts Shopify/shopify_app#895

This PR will be used to address the reason for revert, and original issue.

cc @joshreeves @tanema

### CODE REVIEW

**Comment by joshreeves** [comment]
@hurracrane - I created a PR (#900) that addresses the issues in this branch. I apologize for missing this bug originally.

**Comment by tanema** [comment]
Okay I merged @joshreeves other work into master now. @hurracrane I know your team wants this work. Would you mine testing out this PR with the changes made now?

**Comment by joshreeves** [comment]
@katiedavis @tanema @hurracrane - Hey all, just wanted to clarify that my #900 PR was against this base branch (revert-895-revert.fux.return_to.safari), so that fix is not yet in master until #897 is merged.

**Comment by tanema** [comment]
Yup! Sorry, I miscommunicated that to @hurracrane and he thought it was fixed. His team will be testing this PR with your other fix on master soon so that we can get this merged in as well

**Comment by hurracrane** [comment]
LGTM @Shopify/platform-dev-tools-education can we merge?

**Comment by joshreeves** [comment]
Any progress on getting this merged? @hurracrane @tanema

**Pull request merged**
