### PR TITLE
Update instruction for how to setup `reauth_on_access_scope_changes`

### PR DESCRIPTION
**Pull request by lonroth**
### What this PR does

Update instructions for how to setup `reauth_on_access_scope_changes` in config and controller to make it simpler for others to use this great new functionality. Please see https://github.com/Shopify/shopify_app/issues/1211 for more details.

### CODE REVIEW

**Review by rezaansyed — APPROVED** [review]
@lonroth this is great! Thank you for improving the documentation! 🚀

**Comment by rezaansyed** [comment]
@lonroth in order to move your PR forward, we're going to need you to sign the [CLA](https://cla.shopify.com/)

**Comment by lonroth** [comment]
@rezaansyed I sign it yesterday after the PR was created. I just you just need to rerun the CLA test? Thanks

**Comment by rezaansyed** [comment]
@lonroth I believe you will need to push an empty commit up in order to have the build running again.

**Comment by rezaansyed** [comment]
@lonroth we pushed a fix so that the builds can run. Could you rebase your fork and push that up again?

**Comment by lonroth** [comment]
@rezaansyed Of course! I've now rebased and pushed. Tests ran successfully so I believe we're ready to merge 👍

**Review by paulomarg — APPROVED** [review]
Looks good to me!

**Pull request merged**
