### PR TITLE
Add Table of Contents to README

### PR DESCRIPTION
**Pull request by ashmaroli**
Add Table of Contents to easily navigate through the README file.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Managed to reset my master branch and create a clean PR with changes to only README

**Comment by kevinhughes27** [comment]
Can you squash the commits? something weird is up:

`git rebase -i HEAD~13` then change everything `pick` to `f` except the first one Change it to `r` and then quit your editor. Then re-write the first commit to say `Add Table of Contents to README`

**Comment by ashmaroli** [comment]
I did all that and now my local master and origin/master have diverged, and have 1 and 28 different commits each, respectively

**Comment by kevinhughes27** [comment]
you'll need to force push after the rebase

**Comment by kevinhughes27** [comment]
you could also cherry-pick the table of contents commit to a new branch
`git cherry-pick 589639f`

**Pull request closed without merging**
