### PR TITLE
#674: Allow user agent to not be set

### PR DESCRIPTION
**Pull request by marisveide**
Should resolve the https://github.com/Shopify/shopify_app/issues/674#issuecomment-440429018

### CODE REVIEW

**Comment by marisveide** [comment]
What about that CLA status?
I have filled in that agreement yesterday, but how long does it take to process?

Thanks!

**Comment by ragalie** [comment]
@marisveide would you mind giving the CLA signing another try? I'm not sure why it didn't pick it up; if it still doesn't work after a retry we can move forward. Thanks!

**Comment by marisveide** [comment]
@ragalie - sure, doing it now!

**Comment by marisveide** [comment]
I am signing the Corporate CLA - maybe that's the issue?

**Comment by marisveide** [comment]
Should I use somewhere my GitHub e-mail, not my company e-mail so that it can link the accounts or something?

**Comment by marisveide** [comment]
When trying to sign, it says to me:
> To sign our CLA 1 field needs to be changed
> Contributor's GitHub username is already covered by a corporate CLA

screenshot 2018-12-05 at 18 33 37

**Comment by tylerball** [comment]
@tmlayton can you help out here?

**Comment by tmlayton** [comment]
The GitHub check needs to be manually re-run, otherwise it will be trigger if there is pull request activity (not comments). There is an issue to add this feature https://github.com/Shopify/cla/issues/57

**Comment by marisveide** [comment]
Alright, all checks green.
Will it merge automatically, or somebody will push some button, or I just need to close this pull request and it will get merged? 
Merge options are not showing up for me.

**Comment by tylerball** [comment]
Merged, thanks very much!

**Pull request merged**
