### PR TITLE
easier dependencies

### PR DESCRIPTION
**Pull request by andriytyurnikov**

### CODE REVIEW

**Comment by andriytyurnikov** [comment]
@swalkinshaw check this out

**Comment by andriytyurnikov** [comment]
addition to #272

**Comment by andriytyurnikov** [comment]
@swalkinshaw it will require version bump and release to fix the issue

**Comment by swalkinshaw** [comment]
Thanks. I'm good with this as step 1 👍 

@kevinhughes27 I'll do a follow-up PR to update CI + test matrix

**Comment by kevinhughes27** [comment]
👍

**Pull request merged**
