### PR TITLE
Packaging for release v18.0.3

### PR DESCRIPTION
**Pull request by NabeelAhsen**
### What this PR does

This is a patch release that includes the following bug fixes:

* Change regexp to match standard ngrok URLs. [#1311](https://github.com/Shopify/shopify_app/pull/1311)
* Make `EnsureAuthenticatedLinks` compatible with AppBridge 2.0. [#1277](https://github.com/Shopify/shopify_app/pull/1277)
  * Includes the `host` parameter when redirecting to the splash page in an unauthenticated state.

### Checklist

Before submitting the PR, please consider if any of the following are needed:

- [x] Update `CHANGELOG.md` if the changes would impact users
- [x] Update `README.md`, if appropriate.
- [x] Update any relevant pages in `/docs`, if necessary
- [x] For security fixes, the [Disclosure Policy](https://github.com/Shopify/shopify_app/blob/master/SECURITY.md#disclosure-policy) must be followed.

### CODE REVIEW

**Comment by NabeelAhsen** [comment]
cc @kirillplatonov

**Review by pepicrft — APPROVED** [review]

**Review by jesalerno84 — APPROVED** [review]

**Comment by kirillplatonov** [comment]
@NabeelAhsen In my fork, I also have `ShopifyApp::ShopHost` concern (https://github.com/kirillplatonov/shopify_app/commit/b46ccc1d3607ae0e7aee210c0e79c8ef70866b26) which handles `host` fetching and stores it in cookies. This allows avoiding passing host param manually to every link. I found this concern very convenient and use it in all of my apps. I think it would be great to backport it to this repo too. What do you think?

**Comment by NabeelAhsen** [comment]
@kirillplatonov I saw that as well, and thought it would be neat to have something like this! Although I would rethink the long-term costs of relying on cookies, especially for embedded apps.

This gem has a lot of tech debt to pay regarding an over-reliance on cookies. We can't rely on 3p cookies set by embedded apps in the near future, and so the gem's been slowly trying to phase out any more writes performed on cookies within the gem.

In any case, I don't think it's a blocker to getting this patch released. Thank you for your contributions 🎉 !

What do you think about this release? Is it ready to deploy?

**Comment by kirillplatonov** [comment]
@NabeelAhsen Yeah, let's publish this patch. I will open a PR for `ShopHost` concern so we can discuss all details there.

**Pull request merged**
